name = "conference-slack-form-worker"
main = "src/index.ts"
compatibility_date = "2023-07-10"

[env.development]
name = "conference-slack-form-worker-dev"

[env.production]
name = "conference-slack-form-worker"

# Environment variables (set via wrangler secret put)
# SLACK_BOT_TOKEN - Slack Bot User OAuth Token
# SLACK_TEAM_ID - Your Slack workspace/team ID  
# SLACK_LOG_CHANNEL_ID - Channel ID for logging events
# POSTMARK_API_KEY - Postmark server API key for sending emails
# RATE_LIMIT - Maximum submissions per window per IP/email (e.g., "5")
# RATE_LIMIT_WINDOW_SEC - Rate limit window duration in seconds (e.g., "3600")
